/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package yncrea.isen.cir3

import yncrea.isen.cir3.ctrl.MyArticleDefaultController
import yncrea.isen.cir3.model.IMyArticlesModel
import yncrea.isen.cir3.model.impl.MyDefaultArticleModel
import yncrea.isen.cir3.view.IMyArticlesView
import yncrea.isen.cir3.view.impl.MyView


fun main(args: Array<String>) {
    val articlesModel: IMyArticlesModel = MyDefaultArticleModel();
    val articlesController : MyArticleDefaultController = MyArticleDefaultController(articlesModel)
    val articlesView : IMyArticlesView = MyView(articlesController,"Le Monde")
    articlesController.displayView()
}
